USE [master]
GO

/****** Object:  Database [AlterBank]    Script Date: 17.07.2020 20:10:14 ******/
DROP DATABASE [AlterBank]
GO

/****** Object:  Database [AlterBank]    Script Date: 17.07.2020 20:10:14 ******/
CREATE DATABASE [AlterBank]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AlterBank', FILENAME = N'/var/opt/mssql/data/AlterBank.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AlterBank_log', FILENAME = N'/var/opt/mssql/data/AlterBank_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AlterBank].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AlterBank] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AlterBank] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AlterBank] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AlterBank] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AlterBank] SET ARITHABORT OFF 
GO

ALTER DATABASE [AlterBank] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AlterBank] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AlterBank] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AlterBank] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AlterBank] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AlterBank] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AlterBank] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AlterBank] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AlterBank] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AlterBank] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AlterBank] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AlterBank] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AlterBank] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AlterBank] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [AlterBank] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AlterBank] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [AlterBank] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AlterBank] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AlterBank] SET  MULTI_USER 
GO

ALTER DATABASE [AlterBank] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AlterBank] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AlterBank] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AlterBank] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AlterBank] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AlterBank] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AlterBank] SET  READ_WRITE 
GO


