version: '3.7'

services:
  alterbank-api:
    image: ${REGISTRY:-alterbank}/api:${TAG:-latest}
    container_name: AlterBank_API
    build:
      context: .
      dockerfile: AlterBankApi/Dockerfile
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    container_name: AlterBank_Data